### ISSUE TITLE
Room list filtering

### ISSUE THREAD

**Issue by KB1RD** [KB1RD/matrix-notepad#13]
Currently, all rooms are displayed in the room list. This is a bad idea since the user can easily pick a room that has a long chat history and is not a document. There is talk of creating a room tag or similar for filtering by room type in the issue https://github.com/matrix-org/matrix-doc/issues/423.

**Comment by friedger** [comment]
Maybe include a special room event like for matrix-presents https://github.com/Half-Shot/matrix-presents/blob/master/docs/slide-theory.md

**Comment by KB1RD** [comment]
Added in `v0.2.2`. It is based on the typed rooms MSC (https://github.com/matrix-org/matrix-doc/pull/1840).
